version: '3.9'
services:
  db:
    image: postgres:16-alpine
    container_name: tsn-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tsn_assessment_dev
    ports:
    - 5432:5432
    volumes:
    - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 10
  app:
    build: .
    container_name: tsn-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: '5432'
      DB_NAME: tsn_assessment_dev
      DB_USER: postgres
      DB_PASS: postgres
      PORT: '5000'
      NODE_ENV: production
    ports:
    - 5000:5000
    restart: unless-stopped
volumes:
  pgdata: {}
